### ISSUE TITLE
Create a user-service Kubernetes manifest

### ISSUE THREAD

**Issue by isaschm** [mindtastic/user-service#17]
Our Cluster setup doesn't work with Docker compose. This manifest is to be added to the deploy repo.

**Comment by akkbng** [comment]
@isaschm  this is created in the meeting today by Leo, right?

**Comment by jgraeger** [comment]
> @isaschm this is created in the meeting today by Leo, right?

The user-service got deployed to the cluster by [this PR](https://github.com/mindtastic/deployments/pull/5).
So yeah, this is done :)
