### ISSUE TITLE
Create new endpoints to expose TILT spec

### ISSUE THREAD

**Issue by ldb** [mindtastic/user-service#55]
Each service should expose it's TILT spec.
For each exposed endpoint, we need a new endpoint with the same path suffix, prefixed with `/admin/tilt`. This endpoint should serve the TILT spec for that endpoint and nothing else.

**Comment by akkbng** [comment]
It will be prefixed with `/admin/tilt/user`

**Comment by jgraeger** [comment]
> It will be prefixed with `/admin/tilt/user`

I think it could just be `/tilt`. That it is for the user service is clear from the hostname and it's not an "admin" endpoint in particular. It could be helpful if that Path to fetch the TILT data is the same for all services, especially if we want to "iterate" over all services on a service mesh level.

**Comment by ldb** [comment]
We still need to include the `/user` suffix because we will potentially return different documents for different endpoints (e.g only one endpoints accepts notificationID, so we should add that information for only that path's spans in OTEL).
