### ISSUE TITLE
Add app folder structure

### ISSUE THREAD

**Issue by isaschm** [mindtastic/user-service#9]
So far, we put everything into main.py.
Think about a good way of structuring /app

**Comment by akkbng** [comment]
> Folder structure suggestion for the user-service
 
```
user-service
└── user_service
    └── models
        └── user_model.py
        └── user_settings_model.py
    └── routes
        └── user_routes.py
        └── user_settings_routes.py
    └── __init__.py
    └── app.py
    └── database.py
    └── main.py
└── Dockerfile
└── README.md
└── requirements.txt
```

@isaschm  what do you think? I think separating models and endpoints/routes would make sense, and database.py can be used just to configure DB related stuff.  `main.py` can also be used to run `uvicorn.run("user_service.app:app", host="0.0.0.0", port=8000, reload=True)`, so it's separated from the app's functionality.
